// Metadata:
:description: Week I Learnt
:keywords: study, til, lwil
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font
:hardbreaks:

[[section-202401]]
== 2024년 01월

[[section-202401-5일]]
5일
===
#### event와 command
이벤트(event)는 다음과 같은 특성을 가진다 
- 생산자는 소비자의 consume에 관심이없다. 이벤트를 소비하는것에 무관심하다. 
- 과거에 벌어진 일이기에 검증 대상이 아니다 
- 생산자가 정의한다. 소비자가 생산자에 물리적이든 논리적이든 의존한다. 
- 생산자는 소비자를 특정하지않는다 그래서 이벤트를 전송하는것을 발행한다로 표현한다 

명령(commands) 
- 생산자는 소비자의 consume을 신경쓴다. 명령을 소비하는것을 기대한다 
- 소비자는 생산자의 요청을 수행할 수 있는지 검증한다 
- 생산자가 소비자에게 목표,목적 등 의도를 전달한다 
- 생산자는 소비자를 특정한다. 그래서 명령 전송 행위를 보낸다고 표현한다 
- 소비자가 정의한다. 따라서 생산자가 소비자에게 물리적으로 논리적으로 의존한다

---

[[section-202401-11일]]
11일
===
#### 프로세스의 생성과 종료
이번에 복습을 하며 정확히 알게되어 WIL에 기술하여 봅니다.

생성: 프로세스 생성은 보통 부모 프로세스가 fork() 시스템 콜을 사용하여 자식 프로세스를 생성하는 방식으로 이루어집니다. 이때 자식 프로세스는 부모 프로세스의 복사본으로 생성되며, 필요한 경우 exec() 시스템 콜을 통해 다른 프로그램으로 교체될 수 있습니다. 
이렇게 할 경우 부모프로세스가 자식프로세스를 관리하기가 굉장히 쉬워지고 프로세스를 처음부터 생성하는것보다 복사후 덮어씌우는게 더 빠릅니다. 
종료: 프로세스는 작업을 완료하거나 종료 시스템 콜을 통해 종료될 수 있습니다. 프로세스가 종료되면 운영 체제는 해당 프로세스에 할당된 자원을 회수합니다.

---

[[section-202401-13일]]
13일
===
#### 분산 데이터 환경에서 cap를 전부 만족 할 수 없다
분산 데이터 환경에서 cap를 전부 만족 할 수 없다한다. cap는 다음과 같다.

#### 일관성(Consistency): 
일관성은 분산 시스템의 모든 노드가 동일한 데이터 복사본을 볼 때를 의미합니다. 
어떤 노드에서 데이터를 읽으면 항상 가장 최신의 데이터를 읽을 수 있어야 합니다.

#### 가용성(Availability): 
가용성은 모든 요청에 대한 응답이 있어야 함을 의미합니다. 
시스템은 어떤 요청에도 응답을 해야 하며, 응답이 빨라야 합니다.

#### 분할 내성(Partition Tolerance): 
분할 내성은 네트워크 분할이 발생할 때 시스템이 계속 동작해야 함을 의미합니다. 
분산 시스템은 네트워크 문제 또는 노드 간 통신 문제로 인해 분할되었을 때도 일관성과 가용성을 유지해야 합니다.

**`cap 이론` 은 이중에서 2개만 만족 할 수 있다**한다. 
보통 네트워크장애는 예방이 불가하고 컨트롤 할 수 없는 문제이기에 분할 내성을 지키면서 하는것이 일반적입니다 
따라서 cp 시스템혹은 ap 시스템 둘중 하나를 선택하게 되는데 다르게 설명하면 일관성을 포기 할 것인지 가용성을 포기할 것인지에 대한 선택입니다.

---

[[section-202401-14일]]
14일
===
#### 리눅스에서 `모든 것은 파일이다(Everything is a file)`
리눅스에서는 어플리케이션에서 접근 할 수 있는 경로를 제공하기위해 시스템 콜의 경로를 파일디스크립션이라는 형태로 추상화를 제공한다. 그래서 tcp/ip 같은 네트워크도 보면 fd형태로 접속정보를 관리한다.

> 리눅스와 다른 유닉스 계열 운영 체제들은 "모든 것은 파일이다(Everything is a file)"라는 철학을 따릅니다. 이 철학에 따라, 다양한 시스템 자원에 대한 접근을 파일 디스크립터라는 추상화를 통해 제공합니다. 여기에는 일반 파일뿐만 아니라 소켓, 파이프 등도 포함됩니다.  
> 1. **파일 디스크립터**: 파일 디스크립터는 열린 파일, 소켓, 파이프 등을 나타내는 정수입니다. 운영 체제는 이 정수를 사용하여 해당 자원을 관리합니다.  
> 2. **TCP/IP 소켓과 파일 디스크립터**: 리눅스에서 네트워크 소켓(예: TCP/IP 소켓)도 파일처럼 취급됩니다. 소켓을 생성하면 운영 체제는 그 소켓을 나타내는 파일 디스크립터를 반환합니다. 이를 통해 응용 프로그램은 read, write, close와 같은 표준 파일 작업을 소켓에 대해 수행할 수 있습니다.  
> 3. **시스템 콜과 파일 디스크립터**: 파일 디스크립터는 시스템 콜을 통해 생성되고 관리됩니다. 예를 들어, open() 시스템 콜은 파일을 열고 해당 파일의 파일 디스크립터를 반환합니다. 소켓 생성 시에는 socket() 시스템 콜을 사용하며, 이 역시 파일 디스크립터를 반환합니다.  
>
이러한 방식은 다양한 유형의 입출력 자원을 일관된 방식으로 관리할 수 있게 해주며, 응용 프로그램 개발의 복잡성을 줄여줍니다. 리눅스의 이러한 설계 철학은 시스템의 간결함과 효율성을 크게 향상시킵니다.  
from Chat-GPT 

---
[[section-202401-17일]]
17일
===
#### 뮤택스와 세마포어
대표적인 동기화 메커니즘은 뮤텍스와 세머포어의 차이를 설명한다

#### 뮤텍스(Mutex)
- 임계영역에 하나만 접근 가능하다
- 뮤텍스를 소유하면 소유권(잠금)을 가진 작업자(프로세스 or 쓰레드)가 반드시 소유를 해제하여야 한다
- 다른 곳에서 뮤텍스를 소유하면 다른 작업자는 대기해야함

#### 세마포어(Semaphore)
- 임계영역에 하나 이상이 접근 가능하다
- 소유권(잠금)에 대한 해제를 소유권을 보유한 작업자가 아닌 다른 작업자가 해제가 가능하다, 즉 잠금 해제에 대한 제한이 없다
- 카운팅 세미포어와 바이너리 세마포어로도 구분된다.
```
바이너리 세마포어: 값이 0 또는 1인 세마포어로, 뮤텍스와 작동방식이 유사하다.
카운팅 세마포어: 자원에 접근 가능한 최대 수를 정하고 관리한다.
```

---
[[section-202401-19일]]
19일
===
#### @ConditionalOnProperty
조건부 빈 생성을 위한 주석Annotation이다. @ConditionalOnProperty는 주어진 속성(프로퍼티)이 특정한 값을 가질 때만 스프링 빈을 생성하거나 설정하도록 합니다.
yml이나 application.properties에 특정한 값이 있을때만 bean을 등록하게끔 할 수 있다.
문법은 다음고 같다
```kotlin
@Configuration
@ConditionalOnProperty(name = ["myapp.feature.enabled"], havingValue = "true")
class MyFeatureConfiguration {

    @Bean
    fun myFeatureService(): MyFeatureService {
        return MyFeatureService()
    }

}
```

---
[[section-202401-23일]]
23일
===
#### ACID 란? 
ACID(원자성, 일관성, 고립성, 지속성)은 데이터베이스 트랜잭션의 안전성을 보장하기 위한 속성을 나타냅니다. 이것은 데이터베이스 시스템에서 중요한 개념으로, 다음과 같은 4가지 속성을 의미합니다:

- 원자성(Atomicity): 트랜잭션 내의 모든 작업은 전체적으로 완료되거나 전혀 수행되지 않는 것을 보장합니다.
- 일관성(Consistency): 트랜잭션이 실행 전과 후에 데이터베이스는 일관된 상태를 유지해야 합니다.
- 고립성(Isolation): 복수의 트랜잭션이 동시에 실행될 때, 한 트랜잭션은 다른 트랜잭션의 작업에 영향을 받지 않아야 합니다.
- 지속성(Durability): 트랜잭션이 성공적으로 완료된 경우, 그 결과는 영구적으로 저장되어야 합니다.

---
[[section-202401-25일]]
25일
===
#### lseek
lseek 함수는 UNIX 계열 시스템에서 파일 입출력을 제어할 때 사용되는 시스템 호출이다. 
이 함수는 파일의 읽기/쓰기 위치를 변경하는 데 사용되는데 파일 내의 특정 위치로 이동하여 데이터를 읽거나 쓸 때 필요하다. 
java에서도 lseek의 역할을 하는 함수가 있다 `RandomAccessFile` 의 `seek()` 함수이다. 

---
[[section-202401-30일]]
30일
===
#### 인터럽트

인터럽트란?  
소프트웨어 또는 하드웨어에서 os에 현재 실행중인 프로세스를 일시 중지하고 특정 이벤트를 처리하도록 알리는 메커니즘을 말한다.




