// Metadata:
:description: Week I Learnt
:keywords: study, til, lwil
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font
:hardbreaks:


[[section-202502]]
== 2025년 2월

[[section-202502-5일]]
5일
===
### MySQL의 MVCC

MySQL의 MVCC는 Undo Log 기반의 버전 관리를 통해 동작하며, 트랜잭션이 시작될 때 일관된 스냅샷(consistent snapshot) 을 제공한다.

**트랜잭션 ID (Transaction ID, trx_id)**
각 트랜잭션은 고유한 트랜잭션 ID를 가지며, 트랜잭션이 COMMIT될 때 확정됨.
trx_id는 Undo Log 및 MVCC에서 버전 관리에 중요한 역할을 한다.

**Undo Log**
UPDATE, DELETE 같은 DML 연산이 수행될 때 기존 데이터의 **이전 버전(Older Version)**을 Undo Log에 저장한다.
트랜잭션이 스냅샷 기반으로 데이터를 조회할 경우, Undo Log를 참고하여 트랜잭션 시작 시점의 일관된 데이터를 읽을 수 있다.

**Read View**
트랜잭션이 시작될 때 생성되는 일관된 데이터 스냅샷.
현재 트랜잭션에서 볼 수 있는 유효한 트랜잭션 ID 목록을 포함.
REPEATABLE READ에서는 트랜잭션이 끝날 때까지 유지되지만, READ COMMITTED에서는 매 SELECT 시마다 새로운 Read View를 생성한다.

주의) MVCC는 SELECT FOR UPDATE, LOCK IN SHARE MODE 같은 락을 거는 쿼리에는 적용되지 않는다.
이러한 쿼리는 MVCC 대신 **행 잠금(Row Lock)과 갭 잠금(Gap Lock)**을 사용하여 데이터 일관성을 유지한다.

---

[[section-202502-7일]]
7일
===
### aws 오로라 db와 mysql 차이
페일오버 등등 설명하기


[[section-202502-18일]]
18일
===
### DB 트랜잭션이 서드파티 API 호출로 인해 길어질 때 발생하는 문제와 원인
커넥션풀 고갈 문제


[[section-202502-23일]]
23일
===
### SELECT FOR UPDATE 와 LOCK IN SHARE MODE 차이


[[section-202502-24일]]
24일
===
### 자바의 Integer Cache 


[[section-202502-26일]]
26일
===
### 자바 가상 쓰레드의 호출 스택(Call Stack)은 힙(Heap)에 저장된다
https://openjdk.org/jeps/444

Memory use and interaction with garbage collection
The stacks of virtual threads are stored in Java's garbage-collected heap as stack chunk objects. The stacks grow and shrink as the application runs, both to be memory-efficient and to accommodate stacks of depth up to the JVM's configured platform thread stack size. This efficiency is what enables a large number of virtual threads and thus the continued viability of the thread-per-request style in server applications.

