// Metadata:
:description: Week I Learnt
:keywords: study, til, lwil
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font
:hardbreaks:

---
https://github.com/picbel/WIL/blob/main/2024/10/wil.adoc[이전 달]
https://github.com/picbel/WIL/blob/main/2024/12/wil.adoc[다음 달]

[[section-202411]]
== 2024년 11월

[[section-202411-8일]]
8일
===
### Spring Data Redis의 Transaction 설정

#### RedisTemplate의 setEnableTransactionSupport(true) 란?
해당 함수는 RedisTemplate의 enableTransactionSupport 필드를 set하는 함수이고
enableTransactionSupport는 Redis 연산에 트랜잭션 지원을 활성화 하는지를 결정하는 필드이다
해당 설정을 키면 JPA같은 JDBC 트랜잭션에서 Redis 연산도 동일한 트랜잭션 컨텍스트 내에서 커밋 또는 롤백되도록 할 수 있다.
즉, JPA, JDBC 트랜잭션과 함께 Redis 작업을 수행할 때, 같은 트랜잭션 경계를 따라 처리되는 것 처럼 보인다. 예를 들어, JPA 또는 JDBC 작업이 실패하여 롤백될 때 Redis 연산 결과는 조회되지 않습니다.

#### 주의 사항
Redis의 트랜잭션은 흔히 아는 트랜잭션의 특성인 ACID를 보장하지않는다.
위 방법으로는 원자성(Atomicity)만 보장 된다. 즉 CID는 보장되지않으며 그렇게 보이는것일 뿐이다. (엄밀히 말하면 A도 보장은 아닌거같다.)
Redis는 단일 트랜잭션 내에서 명령들을 일괄 처리(MULTI/EXEC)할 수 있을 뿐, RDBMS의 트랜잭션처럼 자동으로 롤백하는 기능은 제한적이다. 
(실제로 EXEC시점에서 명령을 실행시켜도 중간에 실패가나면 실패한 명령을 제외한 다른 명령들은 반영되어있다. 일반적인 RDB처럼 롤백을 지원하지는 않는다. TMI:단순 문법오류는 EXEC 이전에 이미 실행을 거부한다)
MULTI/EXEC 방식은 단순히 MULTI 명령어가 내린 시점에서 Redis의 연산 명령어를 전부 큐에 담은다음 EXEC 명령어가 실행되는 시점에 큐에 담은 명령어를 한번에 실행시키는 방식이다.
명령들이 단계별로 실행되는 도중 그 결과를 바로 확인하거나 사용할 수 없다. *_즉 트랜잭션 내부에서는 Redis의 연산 결과를 직접 사용할 수 없다_* 
따라서 해당 기능을 키고 트랜잭션내에서 Redis의 연산을 하게된다면 *_트랜잭션 내부에서 Redis의 연산 결과를 활용하여 2차 가공하지 않아야 한다_* (조회하면 어차피 null이 온다.)
(WATCH 명령어를 사용해서 키를 읽고 그값에 따라 트랜잭션 실행여부를 결정 할 수 있지만 Spring Data Redis의 enableTransactionSupport와는 큰 연관이 없어보여서 여기선 설명을 생략한다)

아래는 Spring Data Redis의 org.springframework.data.redis.core.ValueOperations.class 의 get 함수 내용이다
```java
	/**
	 * Get the value of {@code key}.
	 *
	 * @param key must not be {@literal null}.
	 * @return {@literal null} when key does not exist or used in pipeline / transaction.
	 * @see <a href="https://redis.io/commands/get">Redis Documentation: GET</a>
	 */
	@Nullable
	V get(Object key);
```
트랜잭션이나 파이프라인 내부에서 사용되면 null을 리턴한다는것이 주석에 안내되어있다.


---

[[section-202411-12일]]
12일
===
### TCP Head-of-Line (HOL) Blocking  문제

TCP에도 Http 1.1과 같은 HOL문제가 있다.
TCP는 데이터를 순서대로 전달해야하는 프로토콜이다.
따라서 중간에 패킷손실이 발생하면 손실된 패킷이 재전송되어 도착할 때까지 뒤에 있는 패킷이 처리되지 못하고 대기한다.
다르게 말하면 패킷손실이 없다면 TCP에서는 HOL문제가 발생되지 않는다.

---

[[section-202411-19일]]
19일
===
### HikariCP 커넥션 시간 설정과 MySQL의 커넥션 타임아웃 설정

HikariCP의 maxLifetime이나 idleTimeout이 MySQL의 wait_timeout보다 길게 설정되면, MySQL이 먼저 커넥션을 종료해도 HikariCP는 이를 유효하다고 간주해 사용할 수 없는 커넥션을 재사용하려고 시도한다. 
이로 인해 Communications link failure와 같은 예외가 발생하며, 성능 저하와 리소스 낭비, 요청 실패 등의 문제가 생길 수 있다. 
이를 방지하려면 HikariCP의 시간 설정을 MySQL wait_timeout보다 짧게 유지해야 합니다.

해결방법

1. **HikariCP 주요 시간 설정**

- **`maximumPoolSize`**: 풀에서 유지할 최대 커넥션 수
  
- **`idleTimeout` (기본값: 10분)**: 커넥션이 유휴 상태로 유지될 최대 시간, 이 시간이 지나면 유휴 커넥션은 풀에서 제거된다.
  → *MySQL의 wait_timeout보다 짧게 설정하는 것이 권장.*

- **`maxLifetime` (기본값: 30분)**: 각 커넥션이 풀에 유지될 수 있는 최대 시간
  → *MySQL의 wait_timeout보다 짧게 설정 필수* (MySQL이 연결을 강제로 종료하기 전에 HikariCP가 안전하게 커넥션을 교체할 수 있다.)

- **`connectionTimeout` (기본값: 30초)**: 풀에서 커넥션을 얻기 위해 기다릴 최대 시간

2. **MySQL 주요 시간 설정**
- **`wait_timeout` (기본값: 28800초 = 8시간)** : MySQL이 유휴 상태의 커넥션을 종료하기 전까지의 대기 시간
  → HikariCP의 `idleTimeout`과 `maxLifetime`보다 길어야 합니다.  

3. **권장 설정**
HikariCP와 MySQL 설정은 다음과 같은 규칙을 따르면 좋다.
* **HikariCP의 `maxLifetime`은 MySQL의 `wait_timeout`보다 짧게 설정해야 한다.**  
** 예:  
     HikariCP `maxLifetime = 1500초 (25분)`  
     MySQL `wait_timeout = 1800초 (30분)`

* **HikariCP의 `idleTimeout`은 MySQL의 `wait_timeout`보다 짧게 설정해야 한다.**  
** 예:  
     HikariCP `idleTimeout = 600초 (10분)`  
     MySQL `wait_timeout = 1800초 (30분)`

* **HikariCP의 `maxLifetime`은 HikariCP의 `idleTimeout`보다 길게 설정해야 한다.**  
** 예:  
     HikariCP `idleTimeout = 600초 (10분)`  
     HikariCP `maxLifetime = 1500초 (25분)`

---

[[section-202411-22일]]
22일
===
### 클러스터 인덱스, 비클러스터형 인덱스
- 클러스터 인덱스는 테이블 전체가 정렬된 인덱스가 되는 방식의 인덱스 종류이다. 실제 데이터와 무리(cluster)를 지어 인덱싱 되므로 클러스터형 인덱스라고 부른다. 데이터와 함께 전체 테이블이 물리적으로 정렬된다. 
하나만 생성된다 주로 pk를 클러스터형 인덱스로 만든다.
데이터행또한 포함한다

- 비클러스터형 인덱스는 보조 인덱스(Secondary Index)라고도 불리며, 클러스터형 인덱스와 다르게 물리적으로 테이블을 정렬하지 않는다. 그 대신 정렬된 별도의 인덱스 페이지를 생성하고 관리한다. 즉, 실제 데이터를 함께 가지고 있지 않다.

---

[[section-202411-30일]]
30일
===
### Java의 I/O와 NIO(Non-blocking I/O)
Java의 I/O와 NIO(Non-blocking I/O)는 두 가지 다른 API 스타일로, 입출력 작업을 수행하기 위해 사용됩니다.

1. 블로킹 vs. 논블로킹:
   - I/O: 블로킹(Blocked) 방식입니다. I/O 작업은 스레드가 블로킹되어 작업이 완료될 때까지 대기합니다.
   - NIO: 논블로킹(Non-blocking) 방식입니다. I/O 작업은 스레드가 블로킹되지 않고 작업을 계속할 수 있습니다. 이벤트를 기반으로 비동기적으로 작업을 처리할 수 있습니다.

2. API 스타일:
   - I/O: I/O 스트림(Stream) 기반으로 동작합니다. 데이터는 byte 또는 문자로 읽고 쓸 수 있습니다. 상대적으로 간단한 API를 제공합니다.
   - NIO: 버퍼(Buffer)와 채널(Channel) 기반으로 동작합니다. 데이터는 버퍼를 통해 읽고 쓸 수 있으며, 채널을 통해 입출력 작업을 수행합니다. 상대적으로 더 복잡한 API를 제공합니다.

3. 처리 방식:
   - I/O: 데이터는 스트림을 통해 순차적으로 처리됩니다. 입출력 작업은 스레드 단위로 처리되며, 데이터 처리를 위한 추상화 수준이 높습니다.
   - NIO: 데이터는 버퍼를 통해 읽고 쓰며, 채널을 통해 입출력 작업을 수행합니다. 데이터 처리에 직접적인 제어를 할 수 있습니다.

4. 동시성 처리:
   - I/O: 블로킹 방식이므로 I/O 작업이 완료될 때까지 해당 스레드는 대기합니다. 따라서, 많은 수의 동시 접속을 처리하기 위해서는 스레드 풀을 사용해야 합니다.
   - NIO: 논블로킹 방식이므로 I/O 작업이 완료될 때까지 스레드가 블로킹되지 않습니다. 비동기 이벤트 모델과 선택기(Selector)를 사용하여 한 개의 스레드로 많은 연결을 처리할 수 있습니다.

5. 사용 시나리오:
   - I/O: 단순한 입출력 작업에 적합하며, 단일 연결 또는 작은 규모의 접속을 처리하는 데 유용합니다.
   - NIO: 대량의 동시 접속을다루는 네트워크 서버 애플리케이션에 효율적입니다. 많은 수의 클라이언트 연결을 동시에 처리해야 하는 경우에 사용됩니다.

Java NIO의 핵심 개념 중 하나는 바로 버퍼(Buffer)입니다. 
데이터는 버퍼에서 읽고 쓰며, 모든 데이터 항목은 버퍼를 통해 처리됩니다.

버퍼는 '다이렉트(Direct)'와 '논-다이렉트(Non-Direct)'로 구분됩니다.

다이렉트 버퍼(Direct Buffer):
다이렉트 버퍼는 시스템의 네이티브 I/O 작업에 직접 접근할 수 있습니다. 이러한 버퍼는 주로 대량의 데이터를 처리하는데 사용되며, 빠른 속도로 데이터를 읽고 쓸 수 있습니다. 다이렉트 버퍼는 Java 힙 바깥에서 메모리를 할당하기 때문에 생성 비용이 높고, 가비지 컬렉션에 영향을 미치지 않습니다. 그러나 효과적으로 사용되면, 다이렉트 버퍼는 중간 복사 단계 없이 직접 운영체제와 상호작용할 수 있어 I/O 작업의 성능을 향상시킬 수 있습니다.

논-다이렉트 버퍼(Non-Direct Buffer):
논-다이렉트 버퍼는 Java 힙 내에서 메모리를 할당합니다. 이는 일반적으로 Java 객체처럼 동작하며, 작은 데이터 양을 처리할 때 유용합니다. 생성 비용이 다이렉트 버퍼보다 적게 들고, 자바의 가비지 컬렉션에 의해 관리됩니다. 그러나 논-다이렉트 버퍼를 사용할 때, 운영체제와 상호작용하기 위해 데이터를 먼저 버퍼로 복사해야 하므로 추가적인 복사 단계가 필요합니다. 이는 I/O 작업의 성능을 약간 저하시킬 수 있습니다.





