// Metadata:
:description: Week I Learnt
:keywords: study, til, lwil
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font
:hardbreaks:

[[section-202312]]
== 2023년 12월

[[section-202312-4일]]
4일
===
### 하이버네이트 6부터는 DISTINCT를 생략한다.

하이버네이트 6부터 DISTINCT를 더 이상 사용하지 않아도 된다고 한다. 
왜냐하면 반환되는 항목의 중복 항목은 이제 하이버네이트에 의해 필터링 되기 때문입니다. 
`QueryHints#HINT_PASS_DISTINCT_THROUGH` 또한 이제 사용하지 않다도 됩니다 
출처: https://docs.jboss.org/hibernate/orm/6.0/migration-guide/migration-guide.html#query-sqm-distinct

---

[[section-202312-7일]]
7일
===
### 스프링의 Bean Scopes
오늘은 스프링의 Bean Scopes 관련 정리이다. 
스프링에선 크게 6개의 범위(scope)가 있고 이중 4개는 web 관련 ApplicationContext를 사용 할 때만 사용 할 수 있다. 
추가로 범위를 사용자가 직접 정의하는 custom scope도 있다. 
기본적인 범위 2개는 아래와 같다. 
- Singleton : 기본값이며 Spring IoC 컨테이너마다 하나의 빈 정의를 하나의 객체 인스턴스로 다루는 범위입니다. 스프링에서 Bean 속성의 기본값입니다. 
- Prototype : 하나의 빈 정의를 여러 개의 객체 인스턴스에서 사용하는 것(요청이 올때마다 생성하여 사용합니다)

#### Singleton Scope
싱글톤 빈은 하나의 공유된 인스턴스만 관리됩니다. 스프링 IoC 컨테이너가 해당 빈 정의에 정의된 객체를 딱 하나만 생성합니다. 
해당개념은 GOF 패턴책에 정의된 싱글톤 패턴과 다릅니다. 

#### Prototype Scope
특정 빈에 대한 요청이 있을때 마다 새로운 인스턴스를 생성합니다. 
다른 범위와 대조적으로 스프링은 프로토타입 빈의 전체 라이프사이클을 관리하지 않습니다. 
스프링은 프로토타입 객체를 인스턴스화하고 구성후에는 추가적인 기록을 하지않습니다. 
따라서 초기화 라이프 사이드 콜백 메서드(@PostConstruct)는 범위와 상관없이 호출되지만 소멸 라이프사이클 콜백(@PreDestroy)는 호출되지 않습니다. 
프로토 타입의 빈의 경우 객체를 정리시에 빈이 보유한 비용이 많이 드는 리소스 해제에 대한 책임을 져야합니다. 
만약 자바의 new를 대체로 프로토타입을 사용한다면 이 지점 이후 모든 라이프사이클 관리는 사용측이 처리해야합니다. 

---

[[section-202312-12일]]
12일
===
### 타임아웃 등 재시도 전략 관련 고민
오늘은 영상을 하나 보다가 생각보다 괜찮은? 방법을 발견했다. 
흔히들 타임아웃과 관련해서 전략을 세운다. 
어쩔수가 없는게 네트워크 혼선이 있을수도있고 잠시 사용량이 몰려서 실제 처리속도가 느려질수도있다. 
여러가지 이유로 시간지연이 나타날수 밖에없다. 하지만 그렇다고 작업이 끝날때까지 무한히 기다릴수도 없다. 
보통 그래서 타임아웃을 두는것이 일반적인데 그러다보니 만약 타임아웃이 낫다면 후처리는 어떻게 해야하는가? 에 대한 고민도 많이 하게된다 
1. 재시도를 한다 
2. 즉시 재시도가 불가능한 경우 실패한 요청의 경우 찾아서 후처리를 한다. (고객에게 알림, 등) 
그런데 만약 타임아웃이 60초라면 이것을 전부다 기다려야할까...? 
서버는 기다려야하지만 만약 클라에서라면 다르게 표현할수 있을것같다. 
가령 서버는 타임아웃을 60초로 기다리지만 클라는 15초 정도만 기다리고 결과가 15초내로 오면 보여주고 그 이상 걸리게 된다면 결과를 클라에 알림을 보내거나 혹은 클라가 폴링형식으로 결과를 조회하는 방식도 UX차원에서 선택할만한 방법인것 같다.

---

[[section-202312-18일]]
18일
===
### Kafka는 어떻게 빠른걸까?
카프카는 어떻게 빠른걸까??? 
카프카는 zero copy라는 방법을 써서 빠르게 데이터를 보낼수있다 
기존의 전송 방식은 disk - os버퍼 → app버퍼 → 소켓버퍼 → nic 버퍼라면 
zero-copy는 disk → os버퍼 → nic버퍼로 바로 데이터를 복사시킨다 java에선 transferTo() 메서드를 이용하면 된다.

출처: 
https://www.youtube.com/watch?v=UNUz1-msbOM&ab_channel=ByteByteGo 
https://colevelup.tistory.com/23

---

[[section-202312-20일]]
20일
===
### kotlin에서의 객체 초기화 순서
코틀린에서 객체의 초기화시 순서는 다음과 같다

1. constructor default argument
2. property / init 둘은 선언 순서에 따라 달라질수있다
3. constructor block

여기서 상속관계가 있다면

1. child constructor default argument
2. parent constructor default argument
3. parent property / init
4. parent constructor block
5. child property / init
6. child constructor block
순으로 진행된다

간단히 요약하자면 부모의 인스턴스를 전부 초기화후 자식의 인스턴스가 초기화 된다.

---
### 코틀린 코루틴 내에서 발생한 자식 코루틴의 예외는 부모 코루틴에게 전파된다.
코루틴 내부에서 수행되는 자식 코루틴에 애러가 생겼을 때 별도의 Exception Handler을 설정해주지 않으면 자식 코루틴은 부모 코루틴까지 취소시키게 된다. 
부모 코루틴이 취소되면 당연히 부모의 자식으로 있는 코루틴이 모두 취소된다.

---

[[section-202312-23일]]
23일
===
### @PostConstruct와 DeadLock
스프링 공식문서에서 @PostConstruct를 잘못 사용하면 DeadLock(데드락) 위험이 있다고 경고한다. 
출처: https://docs.spring.io/spring-framework/reference/core/beans/factory-nature.html

@PostConstruct와 일반적인초기화 메소드는 컨테이너의 싱글톤 생성 잠금(singleton creation lock)내에서 실행된다 한다.
@PostConstruct 메서드가 반환된 후에 빈 인스턴스가 완전히 초기화되고 다른 객체에 공개될 준비가 되었다고 간주됩니다.
이러한 개별 초기화 메서드는 주어진 구성의 상태를 검증하고 가능하다면 주어진 구성에 기반한 일부 데이터 구조를 준비하는것을 목적합니다만 외부 빈에 접근 이나 추가활동은 없어야합니다. 그렇치 않으면 DeadLock(데드락) 위험이 있다 한다.
(아마 Lock 내부에서 초기화 되지않은 Bean을 기다리다가 DeadLock이 날꺼같다)

만약 초기화 작업때 비동기 데이터작업이라던가, 트랜잭션을 관리하는 비용이 큰 일을 한다면 SmartInitializingSingleton.afterSingletonsInstantiated()를 구현하거나 ContextRefreshedEvent에 대응하는 ApplicationListener를 구현하거나 @EventListener(ContextRefreshedEvent.class) 애너테이션을 선언하는것을 권장합니다
이 두 방식은 싱글톤 생성 잠금(singleton creation lock)외부에서 이루어 진다 한다.

[NOTE]
====
Spring 컨테이너는 구성된 초기화 콜백이 빈이 모든 의존성을 제공받은 직후에 호출되도록 보장합니다. 따라서 초기화 콜백은 원시 빈 참조에 대해 호출되며, 이는 AOP 인터셉터 등이 아직 빈에 적용되지 않았음을 의미합니다.
====

---
### Spring의 graceful shutdown
Spring의 web 기반 ApplicationContext 구현은 관련 웹 애플리케이션이 종료될 때 Spring IoC 컨테이너를 우아하게 종료시키기 위한 코드를 이미 포함하고 있습니다.
web이 아니라면 별도의 설정을 해줘야 한다.

---

ApplicationContextAware를 직접 구현하여 빈정보를 등록하는 방법도있는데 해당 방법은 bean이 Spring에 너무 의존적이게 되어 권장되진 않다.

