// Metadata:
:description: Week I Learnt
:keywords: study, til, lwil
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font
:hardbreaks:


[[section-202412]]
== 2024년 12월

[[section-202412-2일]]
2일
===
### TransactionManager 와 Kotlin Coroutine

org.springframework:spring-tx 의 org.springframework.transaction.annotation.Transactinal 의 주석내용
```
* <h3>Transaction Management</h3>
*
* <p>This annotation commonly works with thread-bound transactions managed by a
* {@link org.springframework.transaction.PlatformTransactionManager}, exposing a
* transaction to all data access operations within the current execution thread.
* <b>Note: This does NOT propagate to newly started threads within the method.</b>
*
* <p>Alternatively, this annotation may demarcate a reactive transaction managed
* by a {@link org.springframework.transaction.ReactiveTransactionManager} which
* uses the Reactor context instead of thread-local variables. As a consequence,
* all participating data access operations need to execute within the same
* Reactor context in the same reactive pipeline.
```
위 주석내용을 간단히 요약하면 다음과 같다.

#### PlatformTransactionManager
Thread Local


#### ReactiveTransactionManager
Reactor Context



Spring Data에서 reactor와 코틀린 코루틴을 활용하여 CoroutineCrudRepository를 지원하기도 한다
data에 crud행위를 추상화한 인터페이스인 CrudRepository처럼 코루틴으로 data에 crud행위를 추상화한 인터페이스이다.


https://docs.spring.io/spring-data/relational/reference/kotlin/coroutines.html


---

[[section-202412-4일]]
4일
===
### ALPN
https://datatracker.ietf.org/doc/html/rfc7301
Http 프로토콜을 정하기위한 협상 과정

---

[[section-202412-9일]]
9일
===
### 벌크헤드 패턴

---
[[section-202412-12일]]
12일
===
### 서킷브레이커

---
[[section-202412-18일]]
18일
===
### Java 쓰레드 풀의 active count
헷갈려서 쓴다..
활성화된 active count 구하는법 알자

---
[[section-202412-19일]]
19일
===
### 코틀린 코루틴 디스패처

1. **`Dispatchers.Default`**
   - CPU 집약적인 작업에 적합.
   - 공유된 스레드 풀에서 실행.

2. **`Dispatchers.IO`**
   - I/O 작업(네트워크, 파일)에 최적화.
   - 많은 스레드를 사용하는 풀에서 실행.

3. **`Dispatchers.Main`**
   - 메인 스레드에서 실행.
   - 만약 해당 디스페처에서 동기적인 작업을 실행할시 메인 스레드가 동기적으로 기다림

4. **`Dispatchers.Unconfined`**
   - 특정 스레드에 바인딩되지 않음.
   - 테스트나 간단한 작업에 사용.

5. **커스텀 디스패처**
   - `Executors` 등을 이용해 직접 생성.
   - 특정 요구사항에 맞는 실행 환경 구성.

**사용 예시**: 
- CPU 작업 → `Default`
- I/O 작업 → `IO`
- UI 작업 → `Main`  
`withContext`로 디스패처 변경 가능.
