// Metadata:
:description: Week I Learnt
:keywords: study, til, lwil
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font
:hardbreaks:


[[section-202406]]
== 2024년 06월


[[section-202406-3일]]
3일
===
### 팬텀리드, 반복가능하지않는 조회, 더티리드

팬텀리드, 반복가능하지않는 조회, 더티리드는 트랜잭션내에 격리수준에 따라 일어나는 현상을 말한다.

- 팬텀 리드: 트랜잭션 내에서 동일한 쿼리로 읽었을 때 결과의 개수가 달라지는 것.
- 반복 불가능한 조회: 트랜잭션 내에서 동일한 쿼리로 조회할 때 레코드의 값이 달라지는 것.
- 더티 리드: 다른 트랜잭션에서 커밋되지 않은 상태의 데이터를 조회하는 것.

---
[[section-202406-8일]]
8일
===
### 바운더리 컨텍스트(Bounded Context)

바운더리 컨텍스트는 소프트웨어 시스템 내의 특정한 모델을 정의하는 경계를 의미한다. 
이 경계 내에서 용어와 규칙은 일관되게 유지되며, 외부와의 통신은 명확히 정의된 인터페이스를 통해 이루어집니다.

---

[[section-202406-12일]]
12일
===
### JtaTransactionManager 란?

JtaTransactionManager는 Java Transaction API(JTA)를 사용하여 트랜잭션을 관리하는 스프링 프레임워크의 클래스이다. 
이 클래스는 주로 분산 트랜잭션 관리에 사용되며, 여러 데이터 소스와의 작업을 하나의 트랜잭션으로 묶어 관리할 수 있도록 합니다. 
그러나 JTA의 트랜잭션 관리를 위해서는 XA 트랜잭션을 지원하는 데이터 소스가 필요합니다.
예를 들어 Redis는 XA 트랜잭션을 지원하지 않기 때문에, JtaTransactionManager를 사용하여 Redis에서 직접 트랜잭션을 관리할 수 없습니다.

#### XA Transaction
XA 트랜잭션은 분산 트랜잭션 표준 중 하나로, 여러 자원 관리자가 참여하는 트랜잭션을 조율할 때 사용된다.
XA는 두 가지 주요 단계를 통해 분산 트랜잭션을 관리합니다: 준비(Prepare)와 커밋(Commit)/롤백(Rollback).
RDB의 트랜잭션은 왠만하면 XA Transaction를 구현한다.

#### 번외 : ChainedTransactionManager 란?

ChainedTransactionManager가 deprecate 된 이유 : ChainedTransactionManager는 여러 트랜잭션 관리자를 조정하지만, ThreadLocal로 인해 롤백 시 불일치와 예기치 못한 동작을 초래할 수 있습니다. 특히 두 번째 트랜잭션 관리자 커밋 실패 시 복구가 어렵습니다. 이러한 이유로 ChainedTransactionManager와 관련 패키지를 사용 중단할 예정입니다.

원문 링크 : https://github.com/spring-projects/spring-data-commons/issues/2232

---

[[section-202406-17일]]
17일
===
### Java의 LinkedHashMap과 LRU

LRU캐쉬를 Java에서 구현할때 LinkedHashMap를 이용해서 많이 구현한다.
이때 주의할점이 accessOrder 값을 꼭 true로 지정하여야한다
map의 반복순서를 정하는 값인데
true일 경우 액세스 순서, false일 경우 삽입 순서에 따라 map의 반복순서를 관리합니다.

---

[[section-202406-18일]]
18일
===
### PreparedStatement 동작 방식

PreparedStatement의 set 메서드를 사용하여 파라미터를 바인딩할 때, 실제로는 SQL 문 자체에서 ? 플레이스홀더를 값으로 즉시 변경하는 것이 아니라, 
그 값을 내부적으로 유지하고 있다가 SQL 문을 실행할 때 데이터베이스와 통신하기 위해 바인딩합니다.

추가로 sql 인젝션을 막기위해 java에서는 https://owasp.org/www-community/attacks/SQL_Injection 의 내용을 반영해서 업데이트 된다.

---

[[section-202406-23일]]
23일
===
### 외부 호출을 트랜잭션과 묶을 때 주의점
네트워크 에러 가능성
외부서버 응답 시간 느릴때 문제점 <- 실패 할 수 있다.
트랜잭션 원자성 보장을 위해 실패시 호출 함수 (롤백함수 or 역함수)

트랜잭션을 묶다보면 여러 고민이 생긴다.
단순히 하나의 DB를 가정하면 쉽다.
그러나 여러DB, Redis, Mongo등 여러 서비스를 사용하거나 여기에 추가해 외부서비스 (가령 결제)같은 서비스랑 묶을때도 필요하다.

---

[[section-202406-27일]]
27일
===
explain 값들 보는법





